//
//  TutorialText.swift
//  Loot
//
//  Created by Benjamin Michael on 4/23/24.
//

import Foundation

let page1txt1 = "Loot is a multiplayer card game, where each card has a unique effect. "
                + "The goal of the game is to win a certain amount of rounds "
                + "- accomplishing this by being the last person remaining or by "
                + "having the highest power card when the round ends."
let page1txt2 = "In this tutorial, we will walk you through the basics of how to play, "
                + "as well as how to interact and understand what is happening on the game screen."
let page1txt3 = "Swipe to the left or right to move to the next/previous page!"
let page2txt1 = "There are 16 cards in the deck, each card appearing a set amount of times."
let page2txt2 = "To begin, the deck is shuffled, and then one card is removed face down. "
                + "One card is then dealt, face down, to each player"
let page2txt3 = "Each player is allowed to look at their card. To start the round, "
                + "one player is dealt an additional card."
let page2txt4 = "When the round is over, the winning player is give a token. "
                + "If they have won as many times as determined, they win the game."
let page2txt5 = "When it is your turn, draw one card."
let page2txt6 = "Play one of your cards face up in front on you, enacting whatever effect the card has."
let page2txt7 = "If you are out, you watch the other players for the remainder of the round."
let page2txt8 = "This continues until round is over."
let page4txt1 = "Below is how the main gameplay screen looks:"
let page4txt2 = "In the next few slides, we will walk through what everything on the screen means, "
                + "and how to interact with it properly to get the most out of your experience!"
let page5txt1 = "Firstly, lets look at some of the main items on the screen."
let page5txt2 = "Notice that the player Josh's cards are highlighted, which indicates that it is his turn."
let page5txt3 = "Here we outlined the excluded card, and the round number. The excluded card is a placeholder to "
                + "show the card that was taken out of the deck during shuffling. Next to it, is the round number."
let page5txt4 = "The blue circle outlines the deck, and the stack of winning tokens. The deck is where players are "
                + "dealt their cards."
let page5txt5 = "The green circle outlines your current number of wins. Each player has a win counter, which will "
                + "indicate how many wins a given player has."
let page5txt6 = "The red circle shows your current hand. The cards at the very bottom are yours to play, when it is "
                + "your turn."
let page6txt1 = "There are two main indicators for players. When you see the blue shield, that means the player "
                + "recently played the wishing ring, and are safe from other players. The red X means that the player "
                + "is out of the round."
let page7txt1 = "The yellow rectangle highlights the rulebook. When you click on this, you will see a popup that shows "
                + "you an overview of the sequence of play on the front, and when you tap it you can see the list of "
                + "cards in the deck. When you are done, swipe down to dismiss."
let page8txt1 = "The yellow rectangle outlines the event log. When you click on it, you will see the pop out shown "
                + "below:"
let page8txt2 = "When a new round begins, a new entry is created for it. Everytime an action takes place, eg someone plays "
                + "a card, the turn passes, or someone is out a event will be put into the respective round log. This "
                + "allows you to keep track of the play, and see who is playing what card on who, as well as what card "
                + "was guessed if applicable. You can shrink an indivdual round log by clicking the arrow on the right of "
                + "the round number."
let page9txt1 = "Whenever you click on a face up card, you will see this view. It allows you to inspect the card in "
                + "more detail, reminding you of the effect the card has."
let page10txt1 = "That's it! You can access this tutorial anytime by clicking on the question mark in the upper "
                + "right hand corner. Thanks for making it all the way through."
